### ISSUE TITLE
EC Text Not Pull Through to SF

### ISSUE THREAD

**Issue by AmyL23** [yalla-coop/smf-app-QA-repo#27]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Bug

### Priority

High

### Please describe your issue & include screenshots:

EC box is ticked and when I did the form I wrote out what the ECs were when prompted. However, it hasn't pulled through on SF. Might be because that section on SF is by the grades, which the form didn't take me too when I clicked ECs from not meeting academic criteria. But I was given a box to fill in during application to what ECs were, which hasn't come through. 

Tester Amy

**Comment by Wah-AuSMF** [comment]
@AmyL23 Thanks Amy! - would you mind adding a screenshot or a link to the specific profile on SF? :)

**Comment by egasparini** [comment]
This should have been resolved as the EC section has been moved to **_before_** the grades.
@Wah-AuSMF Can you please validate?

**Comment by Wah-AuSMF** [comment]
@egasparini Yes, this been fixed! 

However, @yeeaqbi:

- [ ] Please update the field name for the Extenuating Circumstances tickbox to 'Extenuating Circumstances Status' - it's a little confusing on the Page Layout at the moment:

<img width="299" alt="image" src="https://github.com/yalla-coop/smf-app-QA-repo/assets/139127398/347c8c98-3557-4274-90cc-570259bf4be3">
